package com.ali.sadapayclone.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.Dp
import ir.kaaveh.sdpcompose.sdp

@Immutable
data class SPSize(
    val width_back_btn: Dp,
    val height_back_btn: Dp,
    val height_progress_bar: Dp,
    val height_input_field: Dp,
    val width_btn_small: Dp,
    val height_btn_small: Dp,
    val height_btn_large: Dp,
    val height_switch: Dp,
    // local sizes
    val size_100: Dp,
    val round_corner: Dp,
    val size_0: Dp,
    val size_1: Dp,
    val size_2: Dp,
    val size_3: Dp,
    val size_4: Dp,
    val size_5: Dp,
    val size_6: Dp,
    val size_7: Dp,
    val size_10: Dp,
    val size_12: Dp,
    val size_15: Dp,
    val size_16: Dp,
    val size_20: Dp,
    val size_25: Dp,
    val size_26: Dp,
    val size_27: Dp,
    val size_30: Dp,
    val size_60: Dp,
    val size_70: Dp,
    val size_320: Dp,
    val size_35: Dp,
    val size_40: Dp,
    val size_50: Dp,
    val size_80: Dp,
    val size_90: Dp,
    val size_95: Dp,
    val size_130: Dp,
    val size_140: Dp,
    val size_145: Dp,
    val size_150: Dp,
    val size_160: Dp,
    val size_170: Dp,
    val size_180: Dp,
    val size_200: Dp,
    val size_280: Dp
)

val LocalSPSize = staticCompositionLocalOf {
    SPSize(
        width_back_btn = Dp.Unspecified,
        height_back_btn = Dp.Unspecified,
        height_progress_bar = Dp.Unspecified,
        height_input_field = Dp.Unspecified,
        width_btn_small = Dp.Unspecified,
        height_btn_small = Dp.Unspecified,
        height_btn_large = Dp.Unspecified,
        height_switch = Dp.Unspecified,
        // local sizes
        size_100 = Dp.Unspecified,
        round_corner = Dp.Unspecified,
        size_0 = Dp.Unspecified,
        size_1 = Dp.Unspecified,
        size_2 = Dp.Unspecified,
        size_3 = Dp.Unspecified,
        size_4 = Dp.Unspecified,
        size_5 = Dp.Unspecified,
        size_6 = Dp.Unspecified,
        size_7 = Dp.Unspecified,
        size_10 = Dp.Unspecified,
        size_12 = Dp.Unspecified,
        size_15 = Dp.Unspecified,
        size_16 = Dp.Unspecified,
        size_20 = Dp.Unspecified,
        size_25 = Dp.Unspecified,
        size_26 = Dp.Unspecified,
        size_27 = Dp.Unspecified,
        size_30 = Dp.Unspecified,
        size_35 = Dp.Unspecified,
        size_40 = Dp.Unspecified,
        size_50 = Dp.Unspecified,
        size_60 = Dp.Unspecified,
        size_70 = Dp.Unspecified,
        size_80 = Dp.Unspecified,
        size_90 = Dp.Unspecified,
        size_95 = Dp.Unspecified,
        size_130 = Dp.Unspecified,
        size_140 = Dp.Unspecified,
        size_145 = Dp.Unspecified,
        size_150 = Dp.Unspecified,
        size_160 = Dp.Unspecified,
        size_170 = Dp.Unspecified,
        size_180 = Dp.Unspecified,
        size_200 = Dp.Unspecified,
        size_280 = Dp.Unspecified,
        size_320 = Dp.Unspecified
    )
}

val size: SPSize
    @Composable
    get() = SPSize(
        width_back_btn = 22.sdp,
        height_back_btn = 22.sdp,
        height_progress_bar = 4.sdp,
        height_input_field = 38.sdp, // make it wrap
        width_btn_small = 114.sdp,
        height_btn_small = 26.sdp,
        height_btn_large = 45.sdp,
        height_switch = 12.sdp,
        // local sizes
        size_100 = 100.sdp,
        round_corner = 8.sdp,
        size_0 = 0.sdp,
        size_1 = 1.sdp,
        size_2 = 2.sdp,
        size_3 = 3.sdp,
        size_4 = 3.sdp,
        size_5 = 5.sdp,
        size_6 = 6.sdp,
        size_7 = 7.sdp,
        size_10 = 10.sdp,
        size_12 = 12.sdp,
        size_15 = 15.sdp,
        size_16 = 16.sdp,
        size_20 = 20.sdp,
        size_25 = 20.sdp,
        size_26 = 26.sdp,
        size_27 = 27.sdp,
        size_30 = 30.sdp,
        size_60 = 60.sdp,
        size_70 = 70.sdp,
        size_320 = 320.sdp,
        size_35 = 35.sdp,
        size_40 = 40.sdp,
        size_50 = 50.sdp,
        size_80 = 80.sdp,
        size_90 = 90.sdp,
        size_95 = 95.sdp,
        size_130 = 130.sdp,
        size_140 = 140.sdp,
        size_145 = 145.sdp,
        size_150 = 150.sdp,
        size_160 = 160.sdp,
        size_170 = 170.sdp,
        size_180 = 180.sdp,
        size_200 = 200.sdp,
        size_280 = 280.sdp
    )
